import type { Workspace } from "@/lib/types";

const NOW = Date.parse("2026-09-23T21:00:00.000Z");

const hoursAgo = (hours: number) =>
  new Date(NOW - hours * 60 * 60 * 1000).toISOString();

export const PROJECT_COLORS = [
  "#5E6AD2",
  "#26B5CE",
  "#4CB782",
  "#F2C94C",
  "#F2994A",
  "#EB5757",
  "#BB87FC",
];

export function createSeedWorkspace(): Workspace {
  return {
    people: [
      {
        id: "p-maya",
        name: "Maya Chen",
        initials: "MC",
        role: "Staff engineer",
        color: "#5E6AD2",
      },
      {
        id: "p-jordan",
        name: "Jordan Lee",
        initials: "JL",
        role: "Product engineer",
        color: "#26B5CE",
      },
      {
        id: "p-sam",
        name: "Sam Okonkwo",
        initials: "SO",
        role: "Mobile engineer",
        color: "#F2994A",
      },
      {
        id: "p-riley",
        name: "Riley Patel",
        initials: "RP",
        role: "Design engineer",
        color: "#EB5757",
      },
    ],
    labels: [
      { id: "l-bug", name: "Bug", color: "#EB5757" },
      { id: "l-feature", name: "Feature", color: "#5E6AD2" },
      { id: "l-infra", name: "Infra", color: "#F2994A" },
      { id: "l-design", name: "Design", color: "#BB87FC" },
      { id: "l-perf", name: "Perf", color: "#4CB782" },
    ],
    projects: [
      {
        id: "proj-api",
        name: "API Platform",
        key: "API",
        description:
          "Shared auth, billing, and rate-limiting services used by every product.",
        color: "#5E6AD2",
        createdAt: hoursAgo(240),
        columns: [
          { id: "api-backlog", name: "Backlog", wipLimit: null },
          { id: "api-todo", name: "Todo", wipLimit: null },
          { id: "api-progress", name: "In Progress", wipLimit: 3 },
          { id: "api-review", name: "In Review", wipLimit: 4 },
          { id: "api-done", name: "Done", wipLimit: null },
        ],
      },
      {
        id: "proj-mobile",
        name: "Field App",
        key: "MOB",
        description:
          "iOS and Android client for on-site engineers. Offline-first, push-heavy.",
        color: "#26B5CE",
        createdAt: hoursAgo(180),
        columns: [
          { id: "mob-backlog", name: "Backlog", wipLimit: null },
          { id: "mob-todo", name: "Todo", wipLimit: null },
          { id: "mob-progress", name: "In Progress", wipLimit: 3 },
          { id: "mob-review", name: "In Review", wipLimit: 4 },
          { id: "mob-done", name: "Done", wipLimit: null },
        ],
      },
      {
        id: "proj-web",
        name: "Marketing Site",
        key: "WEB",
        description:
          "Public site, docs search, and changelog. Shipping the new pricing page.",
        color: "#4CB782",
        createdAt: hoursAgo(90),
        columns: [
          { id: "web-backlog", name: "Backlog", wipLimit: null },
          { id: "web-todo", name: "Todo", wipLimit: null },
          { id: "web-progress", name: "In Progress", wipLimit: 3 },
          { id: "web-review", name: "In Review", wipLimit: 4 },
          { id: "web-done", name: "Done", wipLimit: null },
        ],
      },
    ],
    issues: [
      {
        id: "i-api-1",
        projectId: "proj-api",
        number: 14,
        title: "Token refresh races when two tabs share a session",
        description:
          "If a user has the dashboard open in two tabs, both try to rotate the refresh token at the same time and one session is signed out. Need a lock in Redis or rotate with reuse detection.",
        status: "api-progress",
        priority: "urgent",
        assigneeId: "p-maya",
        labelIds: ["l-bug", "l-infra"],
        storyPoints: 8,
        order: 0,
        createdAt: hoursAgo(30),
        updatedAt: hoursAgo(2),
      },
      {
        id: "i-api-2",
        projectId: "proj-api",
        number: 18,
        title: "Fairness for bursty rate limits on partner keys",
        description:
          "Partner traffic arrives in spikes and starves product traffic on the shared limiter. Split buckets by key class.",
        status: "api-progress",
        priority: "high",
        assigneeId: "p-jordan",
        labelIds: ["l-infra", "l-perf"],
        storyPoints: 5,
        order: 1,
        createdAt: hoursAgo(48),
        updatedAt: hoursAgo(5),
      },
      {
        id: "i-api-3",
        projectId: "proj-api",
        number: 21,
        title: "Idempotency keys on billing webhooks",
        description:
          "Stripe retries are creating duplicate invoices when the worker restarts mid-handler.",
        status: "api-todo",
        priority: "high",
        assigneeId: "p-maya",
        labelIds: ["l-bug"],
        storyPoints: 5,
        order: 0,
        createdAt: hoursAgo(20),
        updatedAt: hoursAgo(20),
      },
      {
        id: "i-api-4",
        projectId: "proj-api",
        number: 9,
        title: "OpenAPI spec for the v2 search endpoint",
        description:
          "Mobile and web are guessing at query params. Publish a generated spec from the handler types.",
        status: "api-todo",
        priority: "medium",
        assigneeId: "p-jordan",
        labelIds: ["l-feature"],
        storyPoints: 3,
        order: 1,
        createdAt: hoursAgo(72),
        updatedAt: hoursAgo(26),
      },
      {
        id: "i-api-5",
        projectId: "proj-api",
        number: 6,
        title: "Audit log export for enterprise workspaces",
        description:
          "CSV export of auth events for the last 90 days. Needs pagination and a signed download URL.",
        status: "api-backlog",
        priority: "medium",
        assigneeId: null,
        labelIds: ["l-feature"],
        storyPoints: 8,
        order: 0,
        createdAt: hoursAgo(96),
        updatedAt: hoursAgo(96),
      },
      {
        id: "i-api-6",
        projectId: "proj-api",
        number: 22,
        title: "Drop unused GraphQL fields on Project",
        description:
          "legacyOwner and boardTheme are still in the schema and confusing clients.",
        status: "api-backlog",
        priority: "low",
        assigneeId: null,
        labelIds: ["l-infra"],
        storyPoints: 2,
        order: 1,
        createdAt: hoursAgo(12),
        updatedAt: hoursAgo(12),
      },
      {
        id: "i-api-7",
        projectId: "proj-api",
        number: 11,
        title: "P95 latency on /issues list under 120ms",
        description:
          "Add a covering index on (project_id, status, sort_order) and stop hydrating labels in the list query.",
        status: "api-review",
        priority: "high",
        assigneeId: "p-maya",
        labelIds: ["l-perf"],
        storyPoints: 5,
        order: 0,
        createdAt: hoursAgo(54),
        updatedAt: hoursAgo(8),
      },
      {
        id: "i-api-8",
        projectId: "proj-api",
        number: 4,
        title: "Rotate staging secrets out of the old vault path",
        description:
          "Completed. Staging now reads from the 2026 vault mount; old path is deleted.",
        status: "api-done",
        priority: "high",
        assigneeId: "p-jordan",
        labelIds: ["l-infra"],
        storyPoints: 3,
        order: 0,
        createdAt: hoursAgo(200),
        updatedAt: hoursAgo(40),
      },
      {
        id: "i-mob-1",
        projectId: "proj-mobile",
        number: 31,
        title: "Offline cache does not invalidate after a push",
        description:
          "A job-status push arrives, the badge updates, but the job detail screen still shows the stale SQLite row until force-quit.",
        status: "mob-progress",
        priority: "urgent",
        assigneeId: "p-sam",
        labelIds: ["l-bug"],
        storyPoints: 8,
        order: 0,
        createdAt: hoursAgo(18),
        updatedAt: hoursAgo(1),
      },
      {
        id: "i-mob-2",
        projectId: "proj-mobile",
        number: 27,
        title: "Deep link into a closed shift from a notification",
        description:
          "Tapping a shift-closed push should open the timesheet, not the inbox.",
        status: "mob-todo",
        priority: "high",
        assigneeId: "p-sam",
        labelIds: ["l-feature"],
        storyPoints: 3,
        order: 0,
        createdAt: hoursAgo(40),
        updatedAt: hoursAgo(14),
      },
      {
        id: "i-mob-3",
        projectId: "proj-mobile",
        number: 19,
        title: "Haptic pattern for scan success vs failure",
        description:
          "Field techs cannot look at the screen while scanning badges. Need distinct haptics.",
        status: "mob-review",
        priority: "medium",
        assigneeId: "p-riley",
        labelIds: ["l-design"],
        storyPoints: 2,
        order: 0,
        createdAt: hoursAgo(60),
        updatedAt: hoursAgo(9),
      },
      {
        id: "i-mob-4",
        projectId: "proj-mobile",
        number: 8,
        title: "Background location permission copy",
        description:
          "App Store review bounced the previous string. Legal approved a new paragraph.",
        status: "mob-backlog",
        priority: "low",
        assigneeId: "p-riley",
        labelIds: ["l-design"],
        storyPoints: 1,
        order: 0,
        createdAt: hoursAgo(110),
        updatedAt: hoursAgo(50),
      },
      {
        id: "i-web-1",
        projectId: "proj-web",
        number: 42,
        title: "Pricing page: annual vs monthly toggle",
        description:
          "Default to annual. Show the monthly equivalent in muted type. Track the toggle in analytics.",
        status: "web-progress",
        priority: "high",
        assigneeId: "p-riley",
        labelIds: ["l-feature", "l-design"],
        storyPoints: 5,
        order: 0,
        createdAt: hoursAgo(22),
        updatedAt: hoursAgo(3),
      },
      {
        id: "i-web-2",
        projectId: "proj-web",
        number: 38,
        title: "Docs search misses heading text",
        description:
          "The indexer only stores paragraph bodies. API reference headings never appear.",
        status: "web-todo",
        priority: "medium",
        assigneeId: "p-jordan",
        labelIds: ["l-bug"],
        storyPoints: 5,
        order: 0,
        createdAt: hoursAgo(36),
        updatedAt: hoursAgo(16),
      },
      {
        id: "i-web-3",
        projectId: "proj-web",
        number: 29,
        title: "Changelog RSS for the status page",
        description:
          "Ops wants a feed they can pipe into Slack without scraping HTML.",
        status: "web-backlog",
        priority: "none",
        assigneeId: null,
        labelIds: ["l-feature"],
        storyPoints: 2,
        order: 0,
        createdAt: hoursAgo(80),
        updatedAt: hoursAgo(80),
      },
      {
        id: "i-web-4",
        projectId: "proj-web",
        number: 17,
        title: "Replace hero video with a static poster on mobile",
        description:
          "Shipped. Autoplay was eating data on field networks.",
        status: "web-done",
        priority: "medium",
        assigneeId: "p-riley",
        labelIds: ["l-perf", "l-design"],
        storyPoints: 3,
        order: 0,
        createdAt: hoursAgo(140),
        updatedAt: hoursAgo(70),
      },
    ],
  };
}
